dist: bionic
sudo: required
language: java
jobs:
  fast_finish: true
  include:
  - build: ppc64le
    os: linux
    arch: ppc64le
    script: mvn install -Dmaven.javadoc.skip=true
    addons:
      apt:
        packages:
        - curl
  - build: s390x
    os: linux
    arch: s390x
    script: mvn install -Dmaven.javadoc.skip=true
    addons:
      apt:
        packages:
        - curl
services:
- docker
before_install:
- sudo apt-get install -y openjdk-11-jdk maven
- curl -s https://rubygems.org/downloads/asciidoctor-2.0.17.gem -o asciidoctor-2.0.17.gem
- gem install --local asciidoctor
script:
- "./.travis/build.sh"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - BRANCH=${TRAVIS_BRANCH:-main}
  - TAG=${TRAVIS_TAG:-latest}
  - DOCKER_REGISTRY=quay.io
  - MVN_ARGS="-B"
  - TESTCONTAINERS_RYUK_DISABLED=TRUE
  - TESTCONTAINERS_CHECKS_DISABLE=TRUE
  - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-${TRAVIS_CPU_ARCH}
  - PATH=$JAVA_HOME/bin:$PATH
